#https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
---
- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution == 'Ubuntu'

#- name: Add an Apt signing key, uses whichever key is at the URL
#  become: true
#  shell: "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"

#- name: Add apt-repo
#  become: true
#  shell: sudo add-apt-repository 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"'

- name: Adding apt repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install azure-cli
  become: true
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ software_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: adding key
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_distribution == 'CentOS'

- name: Add zure-cli repo
  become: true
  yum_repository:
    name: azure-cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    file: /etc/yum.repos.d/azure-cli
  when: ansible_distribution == 'CentOS'

- name: Install the latest version of azure-cli
  become: true
  yum:
    name: azure-cli
    update_cache: yes
    state: latest
  when: ansible_distribution == 'CentOS'
